development:
  adapter: postgresql
  encoding: unicode
  database: behdovrchu_development
  pool: 5
  username: postgres
  password: Janek
  host: 127.0.0.1

test:
  adapter: postgresql
  encoding: unicode
  database: behdovrchu_test
  pool: 5
  username: postgres
  password: Janek
  host: 127.0.0.1

production:
  adapter: postgresql
  encoding: unicode
  database: behdovrchu_production
  pool: 5
  username: postgres
  password: 